<a href="https://colab.research.google.com/github/davidr1008/Day14/blob/main/Day14_Part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [30]:
dataset = pd.read_csv("/content/Wine.csv")

In [31]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25)

In [33]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [34]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)

In [36]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)

classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [37]:
y_pred = classifier.predict(x_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_pred, y_test)
print(cm)
accuracy_score(y_pred, y_test)

[[17  0  0]
 [ 1 16  0]
 [ 0  1 10]]


0.9555555555555556

In [38]:
y_pred

array([1, 2, 1, 3, 2, 2, 2, 3, 1, 2, 1, 1, 2, 1, 2, 3, 2, 1, 1, 1, 1, 3,
       3, 2, 2, 1, 2, 3, 3, 3, 3, 2, 1, 2, 2, 1, 1, 3, 2, 1, 2, 2, 1, 1,
       3])

In [39]:
y_test

array([1, 2, 1, 2, 2, 2, 2, 3, 1, 2, 1, 1, 2, 1, 2, 3, 2, 1, 1, 1, 1, 3,
       3, 2, 2, 1, 2, 3, 3, 3, 3, 2, 1, 2, 2, 1, 1, 3, 2, 1, 1, 2, 1, 1,
       3])